config/routes.rb
Kiwi::Application.routes.draw do
  devise_for :users
  get "ad_email/new"
  get "users/confirm"
  resources :sessions
  resources :subcategories
  resources :ads
  resources :ad_email

  resources :users
  resources :adcategories

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'  

  root :to => 'adcategories#index'

end

app/models/ad.rb
class Ad < ActiveRecord::Base  
  belongs_to :adcategory
end

app/models/adcategory.rb
class Adcategory < ActiveRecord::Base  
  has_many :subcategories
  has_many :categories, :through => :subcategories
  has_ancestry
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  attr_accessible :adcategory_id, :subcat_id
  belongs_to :adcategory
  belons_to :subcategory, :class_name => "Adcategory"

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/ad_email_controller.rb
class AdEmailController < ApplicationController
  def new
  end
end

app/controllers/adcategories_controller.rb
class AdcategoriesController < ApplicationController
  before_action :set_adcategory, only: [:show, :edit, :update, :destroy]

  # GET /adcategories
  # GET /adcategories.json
  def index
    @adcategories = Adcategory.all
  end

  # GET /adcategories/1
  # GET /adcategories/1.json
  def show
  end

  # GET /adcategories/new
  def new
    @adcategory = Adcategory.new
  end

  # GET /adcategories/1/edit
  def edit
  end

  # POST /adcategories
  # POST /adcategories.json
  def create
    @adcategory = Adcategory.new(adcategory_params)

    respond_to do |format|
      if @adcategory.save
        format.html { redirect_to @adcategory, notice: 'Adcategory was successfully created.' }
        format.json { render action: 'show', status: :created, location: @adcategory }
      else
        format.html { render action: 'new' }
        format.json { render json: @adcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adcategories/1
  # PATCH/PUT /adcategories/1.json
  def update
    respond_to do |format|
      if @adcategory.update(adcategory_params)
        format.html { redirect_to @adcategory, notice: 'Adcategory was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @adcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adcategories/1
  # DELETE /adcategories/1.json
  def destroy
    @adcategory.destroy
    respond_to do |format|
      format.html { redirect_to adcategories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adcategory
      @adcategory = Adcategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adcategory_params
      params.require(:adcategory).permit(:name, :description, :parent_id)
    end
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: [:show, :edit, :update, :destroy]

  # GET /ads
  # GET /ads.json
  def index
    @ads = Ad.all
  end

  # GET /ads/1
  # GET /ads/1.json
  def show
    ad = Ad.find_by_id(params[:id])
    session[:current_ad_id] = ad.id
  end

  # GET /ads/new
  def new
    @ad = Ad.new
  end

  # GET /ads/1/edit
  def edit
  end

  # POST /ads
  # POST /ads.json
  def create
    @ad = Ad.new(ad_params)
    
    respond_to do |format|
      if @ad.save
        format.html { render action: 'edit', notice: 'Ad was successfully created.' }
        format.json { render action: 'edit', status: :created, location: @ad }        
      else
        format.html { render action: 'new' }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ads/1
  # PATCH/PUT /ads/1.json
  def update
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to @ad, notice: 'Ad was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1
  # DELETE /ads/1.json
  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to ads_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ad_params
      params.require(:ad).permit(:name, :adcategory_id, :description, :price)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
   def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  
  def current_ad
    @current_ad ||= Ad.find(session[:current_ad_id]) if session[:current_ad_id]
  end
  helper_method :current_ad
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  def create
    @subcategory = Subcategory.new(params[:subcategory])
    if @subcategory.save
      redirect_to root_url, :notice => "Successfully created subcategory."
    else
      render :action => 'new'
    end
  end

  def destroy
    @subcategory = Subcategory.find(params[:id])
    @subcategory.destroy
    redirect_to root_url, :notice => "Successfully destroyed subcategory."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/ad_email_helper.rb
module AdEmailHelper
end

app/helpers/adcategories_helper.rb
module AdcategoriesHelper
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ad_email/_form.html.erb
<!--<h1><small>Ad Email New</small></h1>-->

<% flash.each do |key, msg| %>
  <%= content_tag :div, msg, :id => key %>
<% end %>
<%= form_tag ad_email_path do %>
  <div class="field">
    <%= label_tag :your_email_address %><br />
    <% if current_ad and current_user%>		          
	<%= text_field_tag :email, params[:email], :value => current_user.email%>
	<% else %>		          
	<%= text_field_tag :email, params[:email]%>
	<% end %>
    
  </div>
  <div class="field">
    <%= label_tag :message %><br />
    <%= text_area_tag :message %>
  </div>
  <div class="actions"><%= submit_tag "Send email", :class =>"small button" %></div>
<% end %>

app/views/adcategories/_form.html.erb
<%= form_for(@adcategory, :html => {:class => "custom"}) do |f| %>
<div class="row">
 <div class="large-4 columns">
  <% if @adcategory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adcategory.errors.count, "error") %> prohibited this adcategory from being saved:</h2>

      <ul>
      <% @adcategory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br>
    <%= f.collection_select :parent_id, Adcategory.order(:name), :id, :name, :prompt => "Select a parent category", include_blank: true %>
  </div>
  <div class="actions">
    <%= f.submit 'Create category', :class => 'small button'  %>
  </div>
 </div>
</div>
<% end %>

app/views/adcategories/edit.html.erb
<h1>Editing adcategory</h1>

<%= render 'form' %>

<%= link_to 'Show', @adcategory %> |
<%= link_to 'Back', adcategories_path %>

app/views/adcategories/index.html.erb
<!--<h1><small>All Ads category</small></h1>-->
<% content_for :title, "Kiwi Ads" %>
<div id="slide" class="row">	
<div class="large-12 large-centered columns">
	<ul data-orbit>
  <li>
    <%=image_tag ("demo1.jpg")%>
    <div class="orbit-caption">Nature</div>
  </li>
  <li>
    <%=image_tag ("demo2.jpg")%>
    <div class="orbit-caption">Tourism and Other</div>
  </li>
  <li>
    <%=image_tag ("demo3.jpg")%>
    <div class="orbit-caption">Accomodations</div>
  </li>
</ul>
</div>
</div>
<hr>

<div class="row" style="position:absolute; top:250px; left:25px;">
<div class="large-12 columns">
  <%=render "shared/new_ad_horizontal"%>	
</div>     
</div> 

</div>

<footer class="row">
  <div class="large-3 small-12 columns">
      <h5><a>About</a></h5>      
  </div>
  <div class="large-3 small-12 columns">
      <h5><a>FAQ</a></h5>      
  </div>
  <div class="large-3 small-12 columns">
      <h5><a>Kiwi blog</a></h5>      
  </div>
 <div class="large-3 small-12 columns">
      <h5><a>Email Us</a></h5>      
  </div>
          
 </footer>
 
    <!-- End Footer -->
<!--
<div class="row">
<div class="large-12 columns">
<div class="large-10 large-centered columns">
<% @adcategories.roots.each do |adcategory| %>
<div class="small-2 large-4 columns">	
		<%= label_tag(adcategory.name)%>
		<%= render 'shared/sub_categories', categories: adcategory.descendants.arrange %>
</div>
<% end %>
</div>
</div>
</div>-->
<!--
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Parent Id</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @adcategories.each do |adcategory| %>
      <tr>
        <td><%= adcategory.name %></td>
        <td><%= adcategory.description %></td>
        <td><%= adcategory.parent_id %></td>
        <td><%= link_to 'Show', adcategory %></td>
        <td><%= link_to 'Edit', edit_adcategory_path(adcategory) %></td>
        <td><%= link_to 'Destroy', adcategory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Adcategory', new_adcategory_path %>
-->

app/views/adcategories/new.html.erb
<!--<h1><small>Create ad category</small></h1>-->

<%= render 'form' %>

<%= link_to 'Back', adcategories_path %>

app/views/adcategories/show.html.erb
<% content_for :title, @adcategory.name %>
<p id="notice"><%= notice %></p>
<ul id="menu">
	<% Adcategory.roots.each do |category| %>
		<li> <%= link_to category.name, category%></li>
	<%end%>
</ul>
<div id="submenu">
  <%= render 'shared/sub_categories', categories: @adcategory.root.descendants.arrange %>
</div>

<ul id="crumb-container crumbs">
  <% @adcategory.ancestors.each do |category| %>
   <li><%= link_to category.name, category %> | </li>
  <% end %>
</ul>

<p>
  <strong>Name:</strong>
  <%= @adcategory.name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @adcategory.description %>
</p>
<p>
  <strong>Parent ID:</strong>
  <%= @adcategory.parent_id %>
</p>

<%= link_to 'Edit', edit_adcategory_path(@adcategory) %> |
<%= link_to 'Back', adcategories_path %>

app/views/ads/_form.html.erb
<%= form_for(@ad, :html => {:class => "custom"}) do |f| %>
<div class="row">
 <div class="large-12 columns">
	  <% if @ad.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@ad.errors.count, "error") %> prohibited this ad from being saved:</h2>
	
	      <ul>
	      <% @ad.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	<div class="section-container auto" data-section>
  <section>
    <p class="title" data-section-title><a href="#panel1">Ad Information</a></p>
    <div class="content" data-section-content>
    	<div class="small-8">
        <div class="field">
	    <%= f.label :name %><br>
	    <%= f.text_field :name %>
	  </div>
	  <div class="field">
	    <%= f.label :description %><br>
	    <%= f.text_area :description %>
	  </div>
	   <div class="field">
	    <%= f.label :price %><br>
	    <%= f.text_field :price %>
	  </div>
	  <div class="field">
	    <%= f.label :adcategory %><br>
	    <%= f.collection_select :adcategory_id, Adcategory.find(:all), :id, :name, :prompt => "Select a Category" %>
	  </div>
	  </div>
    </div>
  </section>
  <section>
    <p class="title" data-section-title><a href="#panel2">Photo Gallery</a></p>
    <div class="content" data-section-content>
      <ul class="clearing-thumbs" data-clearing>
	  <li><a href="path/to/your/img"><img src="path/to/your/img-th"></a></li>
	  <li><a href="path/to/your/img"><img src="path/to/your/img-th"></a></li>
	  <li><a href="path/to/your/img"><img src="path/to/your/img-th"></a></li>
	 </ul>
    </div>
  </section>
  <section>
    <p class="title" data-section-title><a href="#panel3">Contact Information</a></p>
    <div class="content" data-section-content>
    	<div class="small-8">
        <div class="field">
	    <%= f.label :contact_email %><br>
	    <%= f.text_field :contact_email %>
	  </div>
	  <div class="field">
	    <%= f.label :contact_phone %><br>
	    <%= f.text_area :contact_phone %>
	  </div>
	  <div class="actions">
	    <%= f.submit 'Create Ad', :class => 'small button' %>
	  </div>
    </div>
  </section>

</div>	  
	 </div>
 </div>
<% end %>

app/views/ads/edit.html.erb
<h1>
	<i class="fi-asl"></i>
	<small>Editing ad Information</small>
</h1>

<%= render 'form' %>

<%= link_to 'Show', @ad %> |
<%= link_to 'Back', ads_path %>

app/views/ads/index.html.erb
<h1><small>Listing ads</small></h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Adcategory</th>
      <th>Descriptoin</th>
      <th>Price</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ads.each do |ad| %>
      <tr>
        <td><%= ad.name %></td>
        <td><%= ad.adcategory %></td>
        <td><%= ad.description %></td>
        <td><%= ad.price %></td>
        <td><%= link_to 'Show', ad %></td>
        <td><%= link_to 'Edit', edit_ad_path(ad) %></td>
        <td><%= link_to 'Destroy', ad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ad', new_ad_path %>

app/views/ads/new.html.erb
<!--<h1><small>New ad</small></h1>-->

<%= render 'form' %>

<%= link_to 'Back', ads_path %>

app/views/ads/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
<div class="large-12 columns">
<div class="large-7 columns">
<div class="section-container auto " data-section>
  <section>
    <p class="title" data-section-title><a href="#panel1"><i class="fi-folder"></i>&nbsp;Ad Information</a></p>
    <div class="content" data-section-content>
    	<div class="small-8">
	        <p>
			  <strong>Name:</strong>
			  <%= @ad.name %>
			</p>
			
			<p>
			  <strong>Adcategory:</strong>
			  <%= @ad.adcategory %>
			</p>
			
			<p>
			  <strong>description:</strong>
			  <%= @ad.description %>
			</p>
			
			<p>
			  <strong>price:</strong>
			  <%= @ad.price %>
			</p>
	  </div>
    </div>
  </section>
  <section>
    <p class="title" data-section-title><a href="#panel2"><i class="fi-photo"></i>&nbsp;Photo Gallery</a></p>
    <div class="content" data-section-content>
      <ul class="clearing-thumbs" data-clearing>
	  <li><a href="path/to/your/img"><img src="path/to/your/img-th"></a></li>
	  <li><a href="path/to/your/img"><img src="path/to/your/img-th"></a></li>
	  <li><a href="path/to/your/img"><img src="path/to/your/img-th"></a></li>
	 </ul>
    </div>
  </section>
  <section>
    <p class="title" data-section-title><a href="#panel3"><i class="fi-mail"></i>&nbsp;Contact Information</a></p>
    <div class="content" data-section-content>
    	<div class="small-8">    		
        	<%= render 'ad_email/form' %>        	
    	</div>
  </section>
</div>	
</div>	
<div class="large-5 columns">
	<h5 class="subheader">Sponsored Links</h5>
</div>
</div>	
</div>	  
<div class="clear"/>
<div class="row">
	<div class="large-12 columns">
		<div class="large-7 columns">
			<h5 class="subheader">Ads by category</h5>
			<hr>
		</div>
		<div class="large-5 columns">
			<h5 class="subheader">Similar Ads</h5>
			<hr>
		</div>
	</div>
</div>
<div class="clear"/>
<div class="row">
	<div class="large-12 columns">
		<div class="large-7 columns">
			<h5 class="subheader">Ads by location</h5>
			<hr>
		</div>
		<div class="large-5 columns">
			<h5 class="subheader">social hangout</h5>
			<div>
				<a href="#" class="fc-webicon facebook">Like us on Facebook</a>				
				<a href="#" class="fc-webicon rss small">Keep up with us via RSS</a>
				<a href="#" class="fc-webicon twitter">Follow us on twitter</a>
				<a href="#" class="fc-webicon youtube small">Watch us on YouTube</a>
			</div>
			<hr>
		</div>
	</div>
</div>
<!--
<p>
  <strong>Name:</strong>
  <%= @ad.name %>
</p>

<p>
  <strong>Adcategory:</strong>
  <%= @ad.adcategory %>
</p>

<p>
  <strong>description:</strong>
  <%= @ad.description %>
</p>

<p>
  <strong>price:</strong>
  <%= @ad.price %>
</p>

<%= link_to 'Edit', edit_ad_path(@ad) %> |
<%= link_to 'Back', ads_path %>
-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "PostUp" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

<body>   	  	 	   
<%= render 'shared/user_menu'%>

<%= yield %>

<div id="frm_login" class="reveal-modal small">
 	<%= render 'shared/login'%>	
  	<a class="close-reveal-modal">&#215;</a>
</div>

<div id="frm_new_user" class="reveal-modal small">
 	<%= render 'shared/new_user'%>	
  	<a class="close-reveal-modal">&#215;</a>
</div>

<div id="frm_new_ad" class="reveal-modal small">
 	<%= render 'shared/new_ad'%>	
  	<a class="close-reveal-modal">&#215;</a>
</div>

<%= javascript_include_tag "application" %>

</body>
</html>

app/views/shared/_login.html.erb
<!--<div class="panel radius small">Log In</div>
<% flash.each do |key, msg| %>
  <%= content_tag :div, msg, :id => key %>
<% end %>-->
<%= form_tag sessions_path do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email, params[:email] %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions"><%= submit_tag "Log In", :class =>"small button" %></div>
<% end %>

app/views/shared/_new_ad.html.erb
<%@ad = Ad.new%>
<%= form_for(@ad, :html => {:class => "custom"}) do |f| %>
<div class="row">
 <div class="large-12 columns">
	  <% if @ad.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@ad.errors.count, "error") %> prohibited this ad from being saved:</h2>
	
	      <ul>
	      <% @ad.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	<!--<div class="large-2 columns">-->
	  <div class="field">	    
	    <%= f.text_field :name, :placeholder=> "Ad Name" %>
	  </div>
	 <!--</div>-->
	 <!--<div class="large-3 columns">-->
	  <div class="field">	    
	    <%= f.text_field :description, :placeholder => "Description" %>
	  </div>
	  <!--</div>-->
	  <!--<div class="large-2 columns">-->
	   <div class="field">	    
	    <%= f.text_field :price, :placeholder => "Price" %>
	  </div>
	  <!--</div>-->
	  <!--<div class="large-3 columns">-->
	  <div class="field">	  		    
	    <%= f.collection_select :adcategory_id, Adcategory.find(:all), :id, :name, :prompt => "Select a Category" %>
	  </div>
	  <!--</div>-->
	  <!--<div class="large-2 columns">-->
	  <div class="actions">
	    <%= f.submit 'Create Ad', :class => 'small button' %>
	  </div>
	  <!--</div>-->
	 </div>
 </div>
<% end %>

app/views/shared/_new_user.html.erb
<% @user = User.new%>
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", :class =>'small button' %>
  </div>
<% end %>

app/views/shared/_user_menu.html.erb
<div class="container">
<div class="row">	
    <div class="large-12 columns">      
      	<div class="small-4 columns">        	
          <blockquote>
			  <p><%= link_to "WELCOME", root_url%><cite>PostUp.com</cite></p>
		 </blockquote>
        </div>
        <div class="small-6 columns">        	
          <input type="text" placeholder="Search for ads">
        </div>
        <div class="small-2 columns">
          <a href="#" class="button prefix">Search</a>
        </div>
     </div>      
	
	<div class="large-12 columns">	    
    	 <ul class="right button-group">	    	 	
	     </li><a href="#" data-reveal-id="frm_new_ad" class="button small">Create Ad</a></li> 	 
		 <% if current_user %>
	          <!--</li><%= current_user.email%></li>-->
	          </li><%= link_to "Log Out", logout_path, :class => "button small secondary"%></li>
	       <% else %>
	          </li><a href="#" data-reveal-id="frm_new_user" class="button small">Register</a>
	          </li><a href="#" data-reveal-id="frm_login" class="button small secondary">Login</a></li>          
	       <% end %>	       
	       </li><%= link_to "Contact Us", root_url, :class => "button small secondary"%></li>       
	       </li><%= link_to "Swahili", root_url, :class => "button small secondary"%></li> 
	       </li><%= link_to "French", root_path, :class => "button small secondary"%></li>	       
		 </ul>	
	</div>
	<hr>  
</div>
</div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>